# Generated by Django 5.0 on 2024-04-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speachrecapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default=None, null=True, upload_to='videos/'),
        ),
    ]
