# Generated by Django 5.0 on 2024-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speachrecapp', '0004_rename_video_videoupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='voicerec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=199)),
                ('videos', models.FileField(default=None, null=True, upload_to='videos/')),
                ('VideoTitle', models.CharField(max_length=100)),
                ('audia', models.FileField(upload_to='')),
                ('audioTitle', models.CharField(max_length=100)),
                ('filter_words', models.CharField(max_length=100)),
                ('sentiment_scores', models.IntegerField()),
                ('sentiment_scores_compound', models.CharField(max_length=100)),
                ('RMS', models.IntegerField()),
                ('RMS_threshold', models.CharField(max_length=100)),
                ('Pitch', models.IntegerField()),
                ('percentage_modulation', models.CharField(max_length=100)),
                ('Modulation_rating', models.CharField(max_length=100)),
            ],
        ),
    ]
