# Generated by Django 5.0 on 2024-04-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speachrecapp', '0006_voicerec_sentiment_scores_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerec',
            name='filter_words',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='voicerec',
            name='sentiment_scores',
            field=models.JSONField(),
        ),
    ]
